services:
    _defaults:
        autowire: true

    Oveleon\ContaoAdvancedFormBundle\Controller\AjaxController:
        arguments:
            - '@contao.framework'
        tags:
            - controller.service_arguments
